version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    groups:
      vite-plus:
        patterns:
          - vite
          - vite-plus
          - vitest
    ignore:
      - dependency-name: '@types/node'
        update-types: ['version-update:semver-major']
